gatepass_apply/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from gatepass_apply import views

app_name = 'gatepass_apply'
urlpatterns = [
                  path('apply/', views.apply, name='apply'),
                  path('history/', views.history, name='history'),
                  path('add_item/<id>/', views.add_item, name='add_item'),
                  path('print/<pk>/', views.GeneratePdf.as_view(), name='print'),
                  path('delete/<id>/<gatepass_id>/', views.delete_item, name='delete_item'),
                  path('detail/<id>/', views.gatepass_detail, name='gatepass_detail'),
                  path('gatepass_delete/<id>/', views.gatepass_delete, name='gatepass_delete'),
                  path('gatepass_update/<id>/', views.gatepass_update, name='gatepass_update'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gpm/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index, contact, contactUs
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('gatepass/', include('gatepass_apply.urls')),
                  path('approve/', include('gatepass_approve.urls')),
                  path('manager/', include('manager.urls')), 
                  path('contactUs/', contactUs, name='contactUs'), 
                  path('contact/', contact, name='contact'),


              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gatepass_apply/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User

# Create your models here.

status_choice = (
    ('Pending', "Pending"),
    ('Approved', "Approved"),
    ('Rejected', "Rejected"),
)


class Gatepass(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30, null=True, blank=True)
    last_name = models.CharField(max_length=30, null=True, blank=True)
    roll_no = models.CharField(max_length=20, null=True, blank=True)
    mob_no = models.CharField(max_length=11, null=True, blank=True)
    room_no = models.CharField(max_length=3, null=True, blank=True)
    father_name = models.CharField(max_length=50, null=True, blank=True)
    father_mobile = models.CharField(max_length=11, null=True, blank=True)
    hostel = models.CharField(max_length=5)
    pic = models.ImageField(upload_to='gatepass_apply/pics', null=True, blank=True)

    applied_on = models.DateTimeField(default=datetime.now, blank=True)
    from_date = models.CharField(default="", max_length=30)
    to_date = models.CharField(default="", max_length=30)
    purpose = models.CharField(max_length=500)
    address_during_leave = models.CharField(max_length=100)
    hostel_supervisor = models.CharField(max_length=20, choices=status_choice, default="Pending")
    hostel_supervisor_remark = models.CharField(max_length=500, default="N/A")
    hostel_warden = models.CharField(max_length=20, choices=status_choice, default="Pending")
    hostel_warden_remark = models.CharField(max_length=500, default="N/A")
    hostel_assistant_warden = models.CharField(max_length=20, choices=status_choice, default="Pending")
    hostel_assistant_warden_remark = models.CharField(max_length=500, default="N/A")
    control_room = models.CharField(max_length=20, choices=status_choice, default="Pending")
    control_room_remark = models.CharField(max_length=500, default="N/A")

    def __str__(self):
        return str(self.id)


class Item(models.Model):
    gatepass = models.ForeignKey(Gatepass, on_delete=models.CASCADE)
    detail = models.CharField(max_length=500)
    quantity = models.CharField(max_length=3)
    remark = models.CharField(max_length=500)

gatepass_apply/forms.py
from django import forms
from gatepass_apply.models import Gatepass


class ApplyForm(forms.ModelForm):
    class Meta():
        model = Gatepass
        fields = ('from_date', 'to_date', 'purpose', 'address_during_leave', 'applied_on',)
        widgets = {
            'from_date': forms.TextInput(
                attrs={'class': 'form-control datetimepicker-input', 'data-target': '#datetimepicker1'}),
            'applied_on': forms.TextInput(attrs={'class': 'form-control', }),
            'to_date': forms.TextInput(
                attrs={'class': 'form-control datetimepicker-input', 'data-target': '#datetimepicker2'}),
            'purpose': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
            'address_during_leave': forms.Textarea(attrs={'class': 'form-control', 'rows': '3'}),
        }

gatepass_apply/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from gatepass_apply.forms import ApplyForm
from gatepass_apply.models import Gatepass, Item
from accounts.models import Profile
from django.core.files.base import ContentFile
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from utils import render_to_pdf
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime, timedelta


# Create your views here.
@login_required
def apply(request):
    prof = Profile.objects.all().get(user=request.user)
    if prof.user_type == "Student":
        if request.method == "POST":
            form = ApplyForm(request.POST)
            if form.is_valid():
                gatepass = form.save(commit=False)
                gatepass.user = request.user
                prof = Profile.objects.all().get(user=request.user)
                gatepass.first_name = prof.first_name
                gatepass.last_name = prof.last_name
                gatepass.roll_no = prof.roll_no
                gatepass.mob_no = prof.mob_no
                gatepass.room_no = prof.room_no
                gatepass.father_name = prof.father_name
                gatepass.father_mobile = prof.father_mobile
                gatepass.hostel = prof.hostel
                applied_on = request.POST['applied_on']
                ff = "%Y-%m-%d %H:%M:%S.%f"
                applied_on = datetime.strptime(str(applied_on), ff)
                if prof.pic:
                    gatepass.pic.save('pic.jpeg', prof.pic, save=False)
                gatepass.save()
                return redirect('gatepass_apply:add_item', gatepass.id)
        form = ApplyForm()
        prof = Profile.objects.get(user=request.user)
        context = {'form': form, 'prof': prof}
        return render(request, 'gatepass_apply/apply_form.html', context=context)
    else:
        prof = Profile.objects.all().get(user=request.user)
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def add_item(request, id):
    gatepass = Gatepass.objects.all().get(id=id)
    prof = Profile.objects.all().get(user=request.user)
    if gatepass.user == request.user and prof.user_type == "Student":
        if request.method == "POST":
            Item.objects.filter(gatepass=gatepass).delete()
            gatepass_id = request.POST['gatepass_id']
            count = int(request.POST['count'])
            for i in range(count):
                detail = str(i)
                quantity = str(i + 100)
                remark = str(i + 200)
                print("post req:", request.POST[detail])
                item = Item(gatepass=gatepass, detail=request.POST[detail], quantity=request.POST[quantity],
                            remark=request.POST[remark])
                item.save()
            return redirect('gatepass_apply:history')
        else:
            prof = Profile.objects.get(user=request.user)
            items = Item.objects.all().filter(gatepass=Gatepass.objects.get(id=id))
            context = {'prof': prof, 'items': items, 'id': id}
            return render(request, 'gatepass_apply/add_item.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def delete_item(request, id, gatepass_id):
    gatepass = Gatepass.objects.all().get(id=gatepass_id)
    prof = Profile.objects.all().get(user=request.user)
    item = Item.objects.all().get(id=id)
    if gatepass.user == request.user and prof.user_type == "Student":
        item.delete()
        return redirect('gatepass_apply:add_item', gatepass_id)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def history(request):
    prof = Profile.objects.all().get(user=request.user)
    if prof.user_type == "Student":
        obj = Gatepass.objects.all().filter(user=request.user).order_by('-id')
        prof = Profile.objects.get(user=request.user)

        page = request.GET.get('page', 1)
        paginator = Paginator(obj, 10)
        try:
            obj = paginator.page(page)
        except PageNotAnInteger:
            obj = paginator.page(1)
        except EmptyPage:
            obj = paginator.page(paginator.num_pages)
        context = {'gatepasses': obj, 'prof': prof}
        return render(request, 'gatepass_apply/history.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def gatepass_detail(request, id):
    prof = Profile.objects.all().get(user=request.user)
    pass_detail = Gatepass.objects.all().get(id=id)
    if pass_detail.user == request.user and prof.user_type == "Student":
        items = Item.objects.all().filter(gatepass=pass_detail)
        prof = Profile.objects.get(user=request.user)
        context = {'gatepass': pass_detail, 'items': items, 'prof': prof}
        return render(request, 'gatepass_apply/gatepass_detail.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def gatepass_delete(request, id):
    pas = Gatepass.objects.all().get(id=id)
    if pas.user == request.user:
        pas.delete()
        return redirect('gatepass_apply:history')
    else:
        prof = Profile.objects.all().get(user=request.user)
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def gatepass_update(request, id):
    instance = Gatepass.objects.all().get(id=id)
    if instance.user == request.user:
        if request.method == "POST":
            form = ApplyForm(request.POST, instance=instance)
            if form.is_valid():
                gatepass = form.save(commit=False)
                gatepass.user = request.user
                prof = Profile.objects.all().get(user=request.user)
                gatepass.first_name = prof.first_name
                gatepass.last_name = prof.last_name
                gatepass.roll_no = prof.roll_no
                gatepass.mob_no = prof.mob_no
                gatepass.room_no = prof.room_no
                gatepass.father_name = prof.father_name
                gatepass.father_mobile = prof.father_mobile
                gatepass.hostel = prof.hostel
                gatepass.save()
                return redirect('gatepass_apply:add_item', gatepass.id)
        form = ApplyForm(instance=instance)
        prof = Profile.objects.get(user=request.user)
        context = {'form': form, 'prof': prof}
        return render(request, 'gatepass_apply/apply_form.html', context=context)
    else:
        prof = Profile.objects.all().get(user=request.user)
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


class GeneratePdf(View, LoginRequiredMixin):
    def get(self, request, *args, **kwargs):
        primary = self.kwargs['pk']
        gatepass = Gatepass.objects.all().get(pk=primary)
        items = Item.objects.all().filter(gatepass=gatepass)
        data = {'gatepass': gatepass, 'items': items}
        pdf = render_to_pdf('gatepass_apply/gatepass_print.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

templates/gatepass_apply/apply_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                format: 'DD/MM/YYYY'
            });
        });
        $(function () {
            $('#datetimepicker2').datetimepicker({
                format: 'DD/MM/YYYY'
            });
        });
    </script>

    <div class="row justify-content-center">
        <div class="col-md-12 col-sm-12 col-lg-6">
            <span class="anchor" id="formContact"></span>
            <hr class="my-5">
            <!-- form contact -->
            <div class="card card-outline-secondary">
                <div class="card-header">
                    <h3 class="mb-0">Gatepass Detail</h3>
                </div>
                <div class="card-body">
                    <form autocomplete="off" class="form" role="form" method="POST">
                        {% csrf_token %}
                        <fieldset>
                            {{ form.applied_on.as_hidden }}
                            <div class="row mb-1">
                                <div class="col-lg-6">
                                    <label class="mb-0" for="name2">From Date</label>
                                    <div class="form-group">
                                        <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                                            {{ form.from_date }}
                                            <!--  <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4"/> -->
                                            <div class="input-group-append" data-target="#datetimepicker1"
                                                 data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <label class="mb-0" for="name2">To Date</label>
                                    <div class="form-group">
                                        <div class="input-group date" id="datetimepicker2" data-target-input="nearest">
                                            {{ form.to_date }}
                                            <!--  <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker4"/> -->
                                            <div class="input-group-append" data-target="#datetimepicker2"
                                                 data-toggle="datetimepicker">
                                                <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <label class="mb-0" for="message2">Purpose</label>
                            <div class="row mb-1">
                                <div class="col-lg-12">
                                    {{ form.purpose }}
                                </div>
                            </div>
                            <label class="mb-0" for="message2">Address during leave</label>
                            <div class="row mb-1">
                                <div class="col-lg-12">
                                    {{ form.address_during_leave }}
                                </div>
                            </div>
                            <input class="btn btn-secondary btn-lg float-right" type="submit"
                                   value="Proceed To Add Item">
                        </fieldset>
                    </form>
                </div>
            </div><!-- /form contact -->
        </div><!--/col-->
    </div>

{% endblock %}

templates/gatepass_apply/gatepass_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <h3 style="text-align: center;">Your gatepass ID :{{ gatepass.id }}</h3>
    <hr>
    <br>

    <table class="table table-responsive">

        <tbody>
        <tr>
            <th scope="row">Name:</th>
            <td>{{ gatepass.first_name }} {{ gatepass.last_name }}</td>
            <th scope="row">Roll No:</th>
            <td>{{ gatepass.roll_no }}</td>
        </tr>
        <tr>
            <th scope="row">Mobile No:</th>
            <td>{{ gatepass.mob_no }}</td>
            <th scope="row">Applied On:</th>
            <td>{{ gatepass.applied_on }}</td>
        </tr>
        <tr>
            <th scope="row">Room No:</th>
            <td>{{ gatepass.room_no }}</td>
            <th scope="row">Hostel:</th>
            <td>{{ gatepass.hostel }}</td>
        </tr>
        <tr>

            <th scope="row">Father's name:</th>
            <td>{{ gatepass.father_name }}</td>
            <th scope="row">Father's Mob:</th>
            <td>{{ gatepass.father_mobile }}</td>
        </tr>
        <tr>
            <th scope="row">From Date:</th>
            <td>{{ gatepass.from_date }}</td>
            <th scope="row">To Date:</th>
            <td>{{ gatepass.to_date }}</td>
        </tr>
        </tr>
        <tr>
            <th scope="row">Purpose:</th>
            <td>{{ gatepass.purpose }}</td>
            <th scope="row">Address During Leave:</th>
            <td>{{ gatepass.address_during_leave }}</td>
        </tr>
        <tr>
            <th scope="row">Hostel Supervisor:</th>
            <td>{{ gatepass.hostel_supervisor }}</td>
            <th scope="row">Hostel Supervisor Remark:</th>
            <td>{{ gatepass.hostel_supervisor_remark }}</td>
        </tr>
        <tr>
            <th scope="row">Assistant Warden:</th>
            <td>{{ gatepass.hostel_assistant_warden }}</td>
            <th scope="row">Assistant Warden Remark:</th>
            <td>{{ gatepass.hostel_assistant_warden_remark }}</td>
        </tr>
        <tr>
            <th scope="row">Warden:</th>
            <td>{{ gatepass.hostel_warden }}</td>
            <th scope="row">Warden Remark:</th>
            <td>{{ gatepass.hostel_warden_remark }}</td>
        </tr>
        <tr>
            <th scope="row">Control Room Status:</th>
            <td>{{ gatepass.control_room }}</td>
            <th scope="row">Control Room Remark:</th>
            <td>{{ gatepass.control_room_remark }}</td>
        </tr>
        </tbody>
    </table>

    <h2 style="text-align: center;">Items in your gatepass</h2>
    <hr>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">S.No.</th>
                <th scope="col">Detail</th>
                <th scope="col">Quantity</th>
                <th scope="col">Remark</th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.detail }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.remark }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <br><br>
    <a href="{% url 'gatepass_apply:print' gatepass.id %}">
        <button type="button" class="btn btn-primary"><i class="fas fa-print"></i> Print Gatepass</button>
    </a>
{% endblock %}

templates/gatepass_apply/gatepass_print.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    {% load static %}
    <title>Title</title>
    <style type="text/css" media="print">
        body {
            font-weight: 200;
            font-size: 14px;
        }

        .header {
            font-size: 20px;
            font-weight: 100;
            text-align: center;
            color: #007cae;
        }

        .title {
            font-size: 22px;
            font-weight: 100;
            /* text-align: right;*/
            padding: 10px 20px 0px 20px;
        }

        .title span {
            color: #007cae;
        }

        .details {
            padding: 10px 20px 0px 20px;
            text-align: left !important;
            /*margin-left: 40%;*/
        }

        .hrItem {
            border: none;
            height: 1px;
            /* Set the hr color */
            color: #333; /* old IE */
            background-color: #fff; /* Modern Browsers */
        }


        table {
            border: solid #000 !important;
            border-width: 1px 0 0 1px !important;
        }

        th, td {
            border: solid #000 !important;
            border-width: 0 1px 1px 0 !important;
            height: 30px;
            padding-left: 1px;
            padding-top: 3px;
            text-align: left;;
        }

    </style>
</head>
<body>
<div class='wrapper'>
    <div class='header'>
        <p class='title' style="text-decoration: underline;">Atal Bihari Vajpayee-Indian Institute of Information
            Technology and Management (ABV-IIITM), Gwalior Gatepass </p>
    </div>
</div>
<h2>Gatepass ID:{{ gatepass.id }}</h2>
<table class="print-table" style="border-style: solid;">
    <tr>
        <td><strong>Name:</strong> {{ gatepass.first_name }} {{ gatepass.last_name }}</td>
        <td><strong>Roll No:</strong> {{ gatepass.roll_no }}</td>
    </tr>
    <tr>
        <td><strong>Applied On: </strong>{{ gatepass.applied_on }}</td>
        <td><strong>Mobile No: </strong>{{ gatepass.mob_no }}</td>
    </tr>
    <tr>
        <td><strong>Room No:</strong> {{ gatepass.room_no }}</td>
        <td><strong>Hostel: </strong>{{ gatepass.hostel }}</td>
    </tr>
    <tr>
        <td><strong>Father's name:</strong> {{ gatepass.father_name }}</td>
        <td><strong>Father's Mob:</strong> {{ gatepass.father_mobile }}</td>
    </tr>
    <tr>
        <td><strong>From Date:</strong> {{ gatepass.from_date }}</td>
        <td><strong>To Date:</strong> {{ gatepass.to_date }}</td>
    </tr>
    </tr>
    <tr>
        <td><strong>Purpose:</strong> {{ gatepass.purpose }}</td>
        <td><strong>Address During Leave:</strong> {{ gatepass.address_during_leave }}</td>
    </tr>
    <tr>
        <td><strong>Supervisor:</strong> {{ gatepass.hostel_supervisor }}</td>
        <td><strong>Supervisor Remark:</strong> {{ gatepass.hostel_supervisor_remark }}</td>
    </tr>
    <tr>
        <td><strong>Assistant Warden:</strong> {{ gatepass.hostel_assistant_warden }}</td>
        <td><strong>Assistant Warden Remark:</strong> {{ gatepass.hostel_assistant_warden_remark }}</td>
    </tr>
    <tr>
        <td><strong>Warden:</strong> {{ gatepass.hostel_warden }}</td>
        <td><strong>Warden Remark:</strong> {{ gatepass.hostel_warden_remark }}</td>
    </tr>
    <tr>
        <td><strong>Control Room:</strong> {{ gatepass.control_room }}</td>
        <td><strong>Control Room Remark:</strong> {{ gatepass.control_room_remark }}</td>
    </tr>
</table>
<br>
<h4 style="text-align: center;text-decoration: underline;">Items along with gatepass</h4>
<table>
    <tr>
        <th style="text-align: center;">Details</th>
        <th style="text-align: center;">Quantity</th>
        <th style="text-align: center;">Remark</th>
    </tr>
    {% for item in items %}
        <tr>
            <td>{{ item.detail }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.remark }}</td>
        </tr>
    {% endfor %}
</table>
</div>
</body>
</html>

templates/gatepass_apply/history.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<table class="table table-striped table-responsive">
    <thead>
    <tr>
        <th scope="col">Gatepass ID</th>
        <th scope="col">From Date</th>
        <th scope="col">TO Date</th>
        <th scope="col">Supervisor</th>
        <th scope="col">Assistant Warden</th>
        <th scope="col">Warden</th>
        <th scope="col">Control Room</th>
        <th scope="col">Action</th>

    </tr>
    </thead>
    <tbody>
    {% for g in gatepasses %}
    <tr>
        <th scope="row">{{ g.id }}</th>
        <td>{{ g.from_date }}</td>
        <td>{{ g.to_date }}</td>
        <td>{{ g.hostel_supervisor }}</td>
        <td>{{ g.hostel_assistant_warden }}</td>
        <td>{{ g.hostel_warden }}</td>
        <td>{{ g.control_room }}</td>

        {% ifequal g.hostel_supervisor "Pending" %}
        {% ifequal g.control_room "Pending" %}
        {% ifequal g.hostel_warden "Pending" %}
        {% ifequal g.hostel_assistant_warden "Pending" %}
        <td>
            <a href="{% url 'gatepass_apply:gatepass_detail' g.id %}">
                <button type="button" class="btn btn-info" style="width: 80px;">Detail</button>
            </a>
            <a href="{% url 'gatepass_apply:gatepass_update' g.id %}">
                <button type="button" class="btn btn-warning" style="width: 80px;">Update</button>
            </a>
            <button id="btn-confirm" type="button" class="btn btn-danger" style="width: 80px;">Delete</button>
            <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
                 id="mi-modal">
                <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" id="myModalLabel">Are you sure to delete gatepass?</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true" style="width: 80px;">&times;</span></button>
                        </div>
                        <div class="modal-footer">
                            <a href="{% url 'gatepass_apply:gatepass_delete' g.id %}">
                                <button type="button" class="btn btn-danger" id="modal-btn-si" style="width: 80px;">
                                    Delete
                                </button>
                            </a>
                            <button type="button" class="btn btn-primary" id="modal-btn-no" style="width: 80px;">
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </td>
        {% else %}
        <td>
            <a href="{% url 'gatepass_apply:gatepass_detail' g.id %}">
                <button type="button" class="btn btn-info style=" width: 80px;
                "">Detail</button></a>
            <button type="button" class="btn btn-warning" style="width: 80px;" disabled>Update</button>
            <button type="button" class="btn btn-danger" style="width: 80px;" disabled>Delete</button>
        </td>
        {% endifequal %}
        {% else %}
        <td>
            <a href="{% url 'gatepass_apply:gatepass_detail' g.id %}">
                <button type="button" class="btn btn-info" style="width: 80px;">Detail</button>
            </a>
            <button type="button" class="btn btn-warning" disabled style="width: 80px;">Update</button>
            <button type="button" class="btn btn-danger" disabled style="width: 80px;">Delete</button>
        </td>
        {% endifequal %}
        {% else %}
        <td>
            <a href="{% url 'gatepass_apply:gatepass_detail' g.id %}">
                <button type="button" class="btn btn-info" style="width: 80px;">Detail</button>
            </a>
            <button type="button" class="btn btn-warning" disabled style="width: 80px;">Update</button>
            <button type="button" class="btn btn-danger" disabled style="width: 80px;">Delete</button>
        </td>
        {% endifequal %}
        {% else %}
        <td>
            <a href="{% url 'gatepass_apply:gatepass_detail' g.id %}">
                <button type="button" class="btn btn-info" style="width: 80px;">Detail</button>
            </a>
            <button type="button" class="btn btn-warning" disabled style="width: 80px;">Update</button>
            <button type="button" class="btn btn-danger" disabled style="width: 80px;">Delete</button>
        </td>
        {% endifequal %}
    </tr>
    {{ passes.purpose }}
    {% endfor %}
    </tbody>
</table>

<div class="alert" role="alert" id="result"></div>
<script>
    var modalConfirm = function (callback) {

        $("#btn-confirm").on("click", function () {
            $("#mi-modal").modal('show');
        });

        $("#modal-btn-si").on("click", function () {
            callback(true);
            $("#mi-modal").modal('hide');
        });

        $("#modal-btn-no").on("click", function () {
            callback(false);
            $("#mi-modal").modal('hide');
        });
    };

    modalConfirm(function (confirm) {
        if (confirm) {
            //Acciones si el usuario confirma
            $("#result").html("");
        } else {
            //Acciones si el usuario no confirma
            $("#result").html("");
        }
    });
</script>



{% if gatepasses.has_other_pages %}
    <ul class="pagination">
        {% if gatepasses.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ gatepasses.previous_page_number }}">&laquo;</a>
            </li>
        {% else %}
            <li class="page-item"><a class="page-link" href="#"><span>&laquo;</span></a></li>
        {% endif %}
        {% for i in gatepasses.paginator.page_range %}
            {% if gatepasses.number == i %}
                <li class="active page-item"><span class="page-link">{{ i }} <span
                        class="sr-only ">(current)</span></span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if gatepasses.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ gatepasses.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="page-item"><a class="page-link" href="#"><span>&raquo;</span></a></li>
        {% endif %}
    </ul>
{% endif %}

{% endblock %}