accounts/urls.py
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
                  path('login/', views.user_login, name='user_login'),
                  path('logout/', views.user_logout, name='user_logout'),
                  path('signup/', views.signup, name='user_signup'),
                  path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                       views.activate, name='activate'),
                  path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
                  path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
                  path('update-profile/', views.update_profile, name='update_profile'),
                  path('view-profile/', views.view_profile, name='view_profile'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gatepass_approve/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from gatepass_approve import views

app_name = 'gatepass_approve'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('pending_list/', views.pending_list, name='pending_list'),
                  path('approved_list/', views.approved_list, name='approved_list'),
                  path('rejected_list/', views.rejected_list, name='rejected_list'),
                  path('detail/<id>/', views.gatepass_detail, name='gatepass_detail'),
                  path('print/<pk>/', views.GeneratePdf.as_view(), name='print'),
                  path('approved-supervisor/<id>/', views.approve_gatepass_hostel_supervisor,
                       name='approve_gatepass_hostel_supervisor'),
                  path('approved-warden/<id>/', views.approve_gatepass_hostel_warden,
                       name='approve_gatepass_hostel_warden'),
                  path('approved-assistant-warden/<id>/', views.approve_gatepass_hostel_assistant_warden,
                       name='approve_gatepass_hostel_assistant_warden'),
                  path('approved-controlroom/<id>/', views.approve_gatepass_control_room,
                       name='approve_gatepass_control_room'),
                  path('reject-controlroom/<id>/', views.reject_gatepass_control_room,
                       name='reject_gatepass_control_room'),
                  path('reject-hostel-supervisor/<id>/', views.reject_gatepass_hostel_supervisor,
                       name='reject_gatepass_hostel_supervisor'),
                  path('reject-hostel-warden/<id>/', views.reject_gatepass_hostel_warden,
                       name='reject_gatepass_hostel_warden'),
                  path('reject-hostel-assistant-warden/<id>/', views.reject_gatepass_hostel_assistant_warden,
                       name='reject_gatepass_hostel_assistant_warden'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gpm/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index, contact, contactUs
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('gatepass/', include('gatepass_apply.urls')),
                  path('approve/', include('gatepass_approve.urls')),
                  path('manager/', include('manager.urls')), 
                  path('contactUs/', contactUs, name='contactUs'), 
                  path('contact/', contact, name='contact'),


              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from manager import views

app_name = 'manager'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('list-users/', views.list_users, name='list_users'),
                  path('add-user/', views.add_user, name='add_user'),
                  path('update-user/<id>/', views.update_user, name='update_user'),
                  path('detail/<id>/', views.user_detail, name='user-detail'),
                  path('delete/<id>/', views.del_user, name='delete-user'),
                  path('pending-list/', views.pending_list, name='pending_list'),
                  path('rejected-list/', views.rejected_list, name='rejected_list'),
                  path('approved-list/', views.approved_list, name='approved_list'),
                  path('gatepass-detail/<id>/', views.gatepass_detail, name='gatepass_detail'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from accounts.models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


hostel_choice = (
    ('BH1', 'BH1'),
    ('BH2', 'BH2'),
    ('BH3', 'BH3'),
    ('GH', 'GH'),
)

user_category = (
    ('BH1 Supervisor', 'BH1 Supervisor'),
    ('BH2 Supervisor', 'BH2 Supervisor'),
    ('BH3 Supervisor', 'BH3 Supervisor'),
    ('GH Supervisor', 'GH Supervisor'),
    ('Control Room', 'Control Room'),
    ('Student', 'Student'),
)


class ProfileUpdateForm(forms.ModelForm):
    class Meta():
        model = Profile
        exclude = ('roll_no', 'room_no', 'hostel')
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control'}),
            'roll_no': forms.TextInput(attrs={'placeholder': 'Roll number', 'class': 'form-control'}),
            'mob_no': forms.TextInput(attrs={'placeholder': 'Mobile number', 'class': 'form-control'}),
            'email_id': forms.TextInput(attrs={'placeholder': 'Email-ID', 'class': 'form-control'}),
            'room_no': forms.TextInput(attrs={'placeholder': 'Room number', 'class': 'form-control'}),
            'father_name': forms.TextInput(attrs={'placeholder': 'Father\'s name', 'class': 'form-control'}),
            'father_mobile': forms.TextInput(attrs={'placeholder': 'Father\'s mobile number', 'class': 'form-control'}),
            'hostel': forms.Select(attrs={'class': 'form-control'}),
            'user_type': forms.Select(attrs={'class': 'form-control'}),
            'user': forms.TextInput(attrs={'placeholder': 'User', 'class': 'form-control'}),
        }

manager/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from accounts.models import Profile
from gatepass_apply.models import Gatepass, Item
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from utils import render_to_pdf
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, redirect, get_object_or_404
from manager.forms import ProfileUpdateForm
from accounts.models import Profile
from django.contrib.auth.models import User
from django.db.models import Q
from manager.forms import SignupForm
from django.contrib import messages

# Create your views here.


authorize_users = ["BH1 Supervisor", "BH2 Supervisor", "BH3 Supervisor", "GH Supervisor", "Control Room", "BH1 Warden", \
                   "BH2 Warden", "BH3 Warden", "GH Warden", "BH1 Assistant Warden", "BH2 Assistant Warden",
                   "BH3 Assistant Warden", \
                   "GH Assistant Warden", ]


@login_required
def index(request):
    if request.user.is_superuser:
        prof = Profile.objects.get(user=request.user)
        context = {'prof': prof}
        return redirect('manager:list_users')
    else:
        return HttpResponse("Permission Denied")


@login_required
def list_users(request):
    if request.user.is_superuser:
        users = Profile.objects.all().filter(user_type__in=authorize_users)
        prof = Profile.objects.get(user=request.user)
        context = {'prof': prof, 'users': users}
        return render(request, 'manager/list_user.html', context=context)
    else:
        return HttpResponse("Permission Denied")


@login_required
def update_user(request, id):
    if request.user.is_superuser:
        user = get_object_or_404(Profile, user=get_object_or_404(User, id=id))
        if request.method == "POST":
            form = ProfileUpdateForm(request.POST, request.FILES, instance=user)
            if form.is_valid():
                prof = form.save(commit=False)
                prof.user = get_object_or_404(User, id=request.POST['user'])
                prof.save()
                return redirect('index')
        else:
            form = ProfileUpdateForm(instance=user)
            prof = Profile.objects.get(user=request.user)
            context = {'form': form, 'prof': prof}
            return render(request, 'manager/update_user.html', context)
    else:
        return HttpResponse("Permission Denied")


@login_required
def user_detail(request, id):
    if request.user.is_superuser:
        userd = get_object_or_404(Profile, user=get_object_or_404(User, id=id))
        prof = Profile.objects.get(user=request.user)
        context = {'userd': userd, 'prof': prof}
        return render(request, 'manager/detail.html', context)
    else:
        return HttpResponse("Permission Denied")


@login_required
def del_user(request, id):
    if request.user.is_superuser:
        userd = get_object_or_404(User, id=id)
        userd.delete()
        return redirect('manager:index')
    else:
        return HttpResponse("Permission Denied")


@login_required
def pending_list(request):
    if request.user.is_superuser:
        prof = Profile.objects.get(user=request.user)
        pending_passes = Gatepass.objects.all().exclude(
            Q(hostel_warden="Rejected") | Q(hostel_assistant_warden="Rejected") \
            | Q(hostel_supervisor="Rejected") | Q(control_room="Rejected")).filter(Q(hostel_supervisor="Pending") | \
                                                                                   Q(hostel_warden="Pending") & Q(
            hostel_assistant_warden="Pending") | Q(control_room="Pending")).order_by('-id')
        page = request.GET.get('page', 1)
        paginator = Paginator(pending_passes, 10)
        try:
            pending_passes = paginator.page(page)
        except PageNotAnInteger:
            pending_passes = paginator.page(1)
        except EmptyPage:
            pending_passes = paginator.page(paginator.num_pages)
        context = {'prof': prof, 'pending_passes': pending_passes}
        return render(request, 'manager/pending_list.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def rejected_list(request):
    if request.user.is_superuser:
        prof = Profile.objects.get(user=request.user)
        rejected_passes = Gatepass.objects.all().filter(
            Q(hostel_supervisor="Rejected") | Q(hostel_warden="Rejected") | Q(hostel_assistant_warden="Rejected") | Q(
                control_room="Rejected")).order_by('-id')
        page = request.GET.get('page', 1)
        paginator = Paginator(rejected_passes, 10)
        try:
            rejected_passes = paginator.page(page)
        except PageNotAnInteger:
            rejected_passes = paginator.page(1)
        except EmptyPage:
            rejected_passes = paginator.page(paginator.num_pages)
        context = {'prof': prof, 'rejected_passes': rejected_passes}
        return render(request, 'manager/rejected_list.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def approved_list(request):
    if request.user.is_superuser:
        prof = Profile.objects.get(user=request.user)
        approved_passes = Gatepass.objects.all().exclude(
            Q(hostel_warden="Rejected") | Q(hostel_assistant_warden="Rejected")).filter(
            Q(hostel_supervisor="Approved") & (Q(hostel_warden="Approved") | Q(hostel_assistant_warden="Approved")) & Q(
                control_room="Approved")).order_by('-id')

        page = request.GET.get('page', 1)
        paginator = Paginator(approved_passes, 10)
        try:
            approved_passes = paginator.page(page)
        except PageNotAnInteger:
            approved_passes = paginator.page(1)
        except EmptyPage:
            approved_passes = paginator.page(paginator.num_pages)
        context = {'prof': prof, 'approved_passes': approved_passes}
        return render(request, 'manager/approved_list.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)


@login_required
def add_user(request):
    if request.user.is_superuser:
        prof = Profile.objects.get(user=request.user)
        if request.method == 'POST':
            form = SignupForm(request.POST)
            extendForm = ProfileUpdateForm(request.POST)
            var = "xxx"
            try:
                var = User.objects.all().get(username=request.POST.get('username'))
            except:
                var = "xxx"
            print(var)
            if var != "xxx":
                if User.objects.all().get(username=request.POST.get('username')).is_active:
                    messages.warning(request, 'Account already exist with this username!')
                    return redirect('manager:add_user')
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = True
                user.save()
                profile = Profile(user=user)
                profile.first_name = request.POST['first_name']
                profile.last_name = request.POST['last_name']
                profile.user_type = request.POST['user_type']
                profile.email_id = request.POST['email_id']
                profile.mob_no = request.POST['mob_no']
                profile.save()
                return redirect('manager:list_users')
        else:
            form = SignupForm()
            extendForm = ProfileUpdateForm()
            return render(request, 'manager/signup.html', {'form': form, 'extendForm': extendForm, 'prof': prof})
    else:
        return render(request, 'permission_denied.html', context=context)


@login_required
def gatepass_detail(request, id):
    if request.user.is_superuser:
        pass_detail = Gatepass.objects.all().get(id=id)
        prof = Profile.objects.get(user=request.user)
        items = Item.objects.all().filter(gatepass=pass_detail)
        context = {'gatepass': pass_detail, 'items': items, 'prof': prof, 'type': prof.user_type}
        return render(request, 'manager/gatepass_detail.html', context=context)
    else:
        context = {'prof': prof}
        return render(request, 'permission_denied.html', context=context)

templates/manager/approved_list.html
{% extends 'manager/base.html' %}
{% load static %}
{% block content %}
    <div class="table-responsive">
        <table class="table table-striped table-responsive">
            <thead>
            <tr>
                <th scope="col">Gatepass ID</th>
                <th scope="col">From Date</th>
                <th scope="col">TO Date</th>
                <th scope="col">Supervisor</th>
                <th scope="col">Assistant Warden</th>
                <th scope="col">Warden</th>
                <th scope="col">Control Room</th>
                <th scope="col">View</th>
            </tr>
            </thead>
            <tbody>
            {% for g in approved_passes %}
                <tr>
                    <th scope="row">{{ g.id }}</th>
                    <td>{{ g.from_date }}</td>
                    <td>{{ g.to_date }}</td>
                    <td>{{ g.hostel_supervisor }}</td>
                    <td>{{ g.hostel_assistant_warden }}</td>
                    <td>{{ g.hostel_warden }}</td>
                    <td>{{ g.control_room }}</td>
                    <td>
                        <a href="{% url 'gatepass_approve:gatepass_detail' g.id %}">
                            <button type="button" class="btn btn-info">Detail</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    {% if approved_passes.has_other_pages %}
        <ul class="pagination">
            {% if approved_passes.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ approved_passes.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#"><span>&laquo;</span></a></li>
            {% endif %}
            {% for i in approved_passes.paginator.page_range %}
                {% if approved_passes.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only ">(current)</span></span>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if approved_passes.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ approved_passes.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}

templates/manager/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>| E-hostel Leave Application</title>
    <link rel="icon" href="{% static 'images/icon.png' %}" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- ======================== -->
    <!-- Bootstrap 4 -->
    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
            integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
          integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
            integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    <!-- ========================== -->

    <style type="text">
        {%block style%}

            .inset {
                width: 48px;
                height: 48px;
                border-radius: 50%;
                box-shadow: inset 0 0 0 2px rgba(255, 255, 255, 0.6),
                0 1px 1px rgba(0, 0, 0, 0.1);
                background-color: transparent !important;
                z-index: 999;
            }

            .inset img {
                border-radius: inherit;
                width: inherit;
                height: inherit;
                display: block;
                position: relative;
                z-index: 998;
            }
        {%endblock%}
    </style>
    <style>
        .footers {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: rgb(52, 58, 64);
            color: white;
            text-align: center;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#"> E-hostel Leave Application</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>

        </ul>
        {% if not user.is_authenticated %}
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:user_signup' %}">Register</a>
                </li>
            </ul>
        {% else %}

            <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:add_user' %}"><i class="fas fa-user-plus"></i> Add New
                    User</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:list_users' %}"><i class="fas fa-user-edit"></i> Manage Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:pending_list' %}">Pending Gatepass</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:approved_list' %}">Approved Gatepass</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'manager:rejected_list' %}">Rejected Gatepass</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#">Hi {{ user.username }}</a>
            </li>
            <ul class="navbar-nav mr-auto dropdown-menu-right">
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-cog"></i></a>
                    <div class="dropdown-menu " style="right:0;left: auto;">
                        <a class="dropdown-item" href="{% url 'accounts:view_profile' %}">View Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:update_profile' %}">Update Profile</a>
                        <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
                        <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
            <ul/>
        {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<br><br><br>
<div class="footers">
    <p>Online Hostel Leave Application Portal </p>
</div>
</body>
</html>

templates/manager/detail.html
{% extends 'manager/base.html' %}
{% load static %}
{% static "" as baseUrl %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <div class="card" style="width: 100%; margin-right: auto; margin-left: auto;">
        <br>
        <img class="card-img-top" src="/static{{ baseUrl }}/{{ userd.pic }}" alt="Image is Not Available"
             class="rounded" style="display: block;
  margin-left: auto; margin-right: auto; width: 30%; border: solid;border-radius: 10px; border-width: 1px;">
        <div class="card-body">
            <br>
            <hr>
            <div class="table-responsive">
                <table class="table table-striped ">
                    <thead>
                    </thead>
                    <tbody>
                    <tr>
                        <th scope="row">Name:</th>
                        <td>{{ userd.first_name }} {{ userd.last_name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Mobile No. :</th>
                        <td>{{ userd.mob_no }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email ID :</th>
                        <td>{{ userd.email_id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Designation:</th>
                        <td>{{ userd.user_type }}</td>
                    </tr>
                    <tr>
                        <td><a href="{% url 'manager:update_user' userd.user.id %}">
                            <button type="button" class="btn btn-primary" style="width: 100%"><i
                                    class="far fa-edit"></i> &nbsp Edit
                            </button>
                        </a></td>
                        <td>
                            <button type="button" class="btn btn-danger" style="width: 100%" id="btn-confirm"><i
                                    class="fas fa-trash-alt"></i> &nbsp Delete
                            </button>
                            </a></td>
                    </tr>
                    </tbody>
                </table>
            </div>

        </div>
    </div>

    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
         id="mi-modal">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">Are you sure to delete the user?</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" id="modal-btn-si">Cancel</button>
                    <a href="{% url 'manager:delete-user' userd.user.id %}">
                        <button type="button" class="btn btn-danger" id="modal-btn-no">Delete</button>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="alert" role="alert" id="result"></div>

    <script type="text/javascript">
        var modalConfirm = function (callback) {

            $("#btn-confirm").on("click", function () {
                $("#mi-modal").modal('show');
            });

            $("#modal-btn-si").on("click", function () {
                callback(true);
                $("#mi-modal").modal('hide');
            });

            $("#modal-btn-no").on("click", function () {
                callback(false);
                $("#mi-modal").modal('hide');
            });
        };

        modalConfirm(function (confirm) {
            if (confirm) {
                //Acciones si el usuario confirma
                // $("#result").html("CONFIRMADO");
            } else {
                //Acciones si el usuario no confirma
                // $("#result").html("NO CONFIRMADO");
            }
        });
    </script>

{% endblock %}

templates/manager/index.html
{% extends 'manager/base.html' %}
{% load static %}
{% block content %}
    <h3>This is admin page.</h3>
{% endblock %}

templates/manager/list_user.html
{% extends 'manager/base.html' %}
{% load static %}
{% block content %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Name</th>
                <th scope="col">Mobile No.</th>
                <th scope="col">Designation</th>
                <th scope="col">View</th>
            </tr>
            </thead>
            <tbody>
            {% for u in users %}
                <tr>
                    <th scope="row">{{ u.user }}</th>
                    <td>{{ u.first_name }} {{ u.last_name }} </td>
                    <td>{{ u.mob_no }}</td>
                    <td>{{ u.user_type }}</td>
                    <td>
                        <a href="{% url 'manager:user-detail' u.user.id %}">
                            <button type="button" class="btn btn-primary"><i class="far fa-eye"></i>&nbsp View</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    {% if approved_passes.has_other_pages %}
        <ul class="pagination">
            {% if approved_passes.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ approved_passes.previous_page_number }}">&laquo;</a>
                </li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#"><span>&laquo;</span></a></li>
            {% endif %}
            {% for i in approved_passes.paginator.page_range %}
                {% if approved_passes.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only ">(current)</span></span>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if approved_passes.has_next %}
                <li class="page-item"><a class="page-link"
                                         href="?page={{ approved_passes.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="#"><span>&raquo;</span></a></li>
            {% endif %}
        </ul>
    {% endif %}
{% endblock %}