accounts/urls.py
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'accounts'

urlpatterns = [
                  path('login/', views.user_login, name='user_login'),
                  path('logout/', views.user_logout, name='user_logout'),
                  path('signup/', views.signup, name='user_signup'),
                  path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                       views.activate, name='activate'),
                  path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
                  path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
                  path('update-profile/', views.update_profile, name='update_profile'),
                  path('view-profile/', views.view_profile, name='view_profile'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gatepass_apply/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from gatepass_apply import views

app_name = 'gatepass_apply'
urlpatterns = [
                  path('apply/', views.apply, name='apply'),
                  path('history/', views.history, name='history'),
                  path('add_item/<id>/', views.add_item, name='add_item'),
                  path('print/<pk>/', views.GeneratePdf.as_view(), name='print'),
                  path('delete/<id>/<gatepass_id>/', views.delete_item, name='delete_item'),
                  path('detail/<id>/', views.gatepass_detail, name='gatepass_detail'),
                  path('gatepass_delete/<id>/', views.gatepass_delete, name='gatepass_delete'),
                  path('gatepass_update/<id>/', views.gatepass_update, name='gatepass_update'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gatepass_approve/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from gatepass_approve import views

app_name = 'gatepass_approve'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('pending_list/', views.pending_list, name='pending_list'),
                  path('approved_list/', views.approved_list, name='approved_list'),
                  path('rejected_list/', views.rejected_list, name='rejected_list'),
                  path('detail/<id>/', views.gatepass_detail, name='gatepass_detail'),
                  path('print/<pk>/', views.GeneratePdf.as_view(), name='print'),
                  path('approved-supervisor/<id>/', views.approve_gatepass_hostel_supervisor,
                       name='approve_gatepass_hostel_supervisor'),
                  path('approved-warden/<id>/', views.approve_gatepass_hostel_warden,
                       name='approve_gatepass_hostel_warden'),
                  path('approved-assistant-warden/<id>/', views.approve_gatepass_hostel_assistant_warden,
                       name='approve_gatepass_hostel_assistant_warden'),
                  path('approved-controlroom/<id>/', views.approve_gatepass_control_room,
                       name='approve_gatepass_control_room'),
                  path('reject-controlroom/<id>/', views.reject_gatepass_control_room,
                       name='reject_gatepass_control_room'),
                  path('reject-hostel-supervisor/<id>/', views.reject_gatepass_hostel_supervisor,
                       name='reject_gatepass_hostel_supervisor'),
                  path('reject-hostel-warden/<id>/', views.reject_gatepass_hostel_warden,
                       name='reject_gatepass_hostel_warden'),
                  path('reject-hostel-assistant-warden/<id>/', views.reject_gatepass_hostel_assistant_warden,
                       name='reject_gatepass_hostel_assistant_warden'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gpm/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import index, contact, contactUs
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', index, name='index'),
                  path('accounts/', include('accounts.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('gatepass/', include('gatepass_apply.urls')),
                  path('approve/', include('gatepass_approve.urls')),
                  path('manager/', include('manager.urls')), 
                  path('contactUs/', contactUs, name='contactUs'), 
                  path('contact/', contact, name='contact'),


              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from manager import views

app_name = 'manager'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('list-users/', views.list_users, name='list_users'),
                  path('add-user/', views.add_user, name='add_user'),
                  path('update-user/<id>/', views.update_user, name='update_user'),
                  path('detail/<id>/', views.user_detail, name='user-detail'),
                  path('delete/<id>/', views.del_user, name='delete-user'),
                  path('pending-list/', views.pending_list, name='pending_list'),
                  path('rejected-list/', views.rejected_list, name='rejected_list'),
                  path('approved-list/', views.approved_list, name='approved_list'),
                  path('gatepass-detail/<id>/', views.gatepass_detail, name='gatepass_detail'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>| E-hostel Leave Application</title>
    <link rel="icon" href="{% static 'images/icon.png' %}" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- ======================== -->
    <!-- Bootstrap 4 -->
    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
            integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css"
          integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"
            integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    <!-- ========================== -->

    <style type="text">
        {%block style%}

            {#body, html {#}
            {#    height: 100%;#}
            {#}#}




            .inset {
                width: 48px;
                height: 48px;
                border-radius: 50%;
                box-shadow: inset 0 0 0 2px rgba(255, 255, 255, 0.6),
                0 1px 1px rgba(0, 0, 0, 0.1);
                background-color: transparent !important;
                z-index: 999;
            }

            .inset img {
                border-radius: inherit;
                width: inherit;
                height: inherit;
                display: block;
                position: relative;
                z-index: 998;
            }

        {%endblock%}


    </style>
    <style>
        .back {
            /* The image used */
        {#background-color: gainsboro;#}

            /* Full height */
            height: 100%;

            /* Center and scale the image nicely */
            background-position: center;
            background-repeat: no-repeat;
            background-size: initial;
            margin-top: 25px;
        }

        .column {
            float: left;
            width: 24%;
            padding: 10px;
            margin: 0.5%;
        {#text-align: center;#}

        }

        /* Clear floats after the columns */
        .row:after {
            background-color: gainsboro;
            content: "";
            display: table;
            clear: both;
        }

        @media screen and (max-width: 900px) {
            .column {
                width: 49%;
            }
        }

        @media screen and (max-width: 600px) {
            .column {
                width: 100%;
            }
        }

        .footers {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: rgb(52, 58, 64);
            color: white;
            text-align: center;
        }
    </style>
</head>
<body background="{% static 'pics/2.jpg' %}">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="width: 100%">
    <a class="navbar-brand" href="#">E-hostel Leave Application</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"> 
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'contactUs' %}"><i class="fas fa-contact"></i> Contact Staff <span class="sr-only">(current)</span></a>
            </li>

        </ul>

        </ul>
        {% if not user.is_authenticated %}
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}"><i class="fas fa-sign-in-alt"></i> Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_signup' %}"><i class="fas fa-user-plus"></i>
                    Register</a>
            </li>
        </ul>
        {% else %}
        {% ifequal prof.user_type "Student" %}
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gatepass_apply:apply' %}">Apply Gatepass</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gatepass_apply:history' %}">History</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'contact' %}">Hostel Staff</a>
            </li>

            {% else %}
            {% ifequal prof.user_type "Admin" %}
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:add_user' %}">Add New User</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:list_users' %}">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:pending_list' %}">Pending Gatepass</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:approved_list' %}">Approved Gatepass</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'manager:rejected_list' %}">Rejected Gatepass</a>
                </li>
                {% else %}
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gatepass_approve:pending_list' %}">Pending Gatepass</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gatepass_approve:approved_list' %}">Approved Gatepass</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'gatepass_approve:rejected_list' %}">Rejected Gatepass</a>
                    </li>
                    {% endifequal %}
                    {% endifequal %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Hi, {{ user.username }}!</a>
                    </li>
                    <ul class="navbar-nav mr-auto dropdown-menu-right">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-cog"></i></a>

                            <!-- <img src="{%  static '{{prof.pic}}' %}" class="profile-image rounded-circle" style="width: 30px; height: 30px;"> -->
                            <div class="dropdown-menu specific " style="right:0;left: auto;">
                                <a class="dropdown-item" href="{% url 'accounts:view_profile' %}">View Profile</a>
                                <a class="dropdown-item" href="{% url 'accounts:update_profile' %}">Update Profile</a>
                                <a class="dropdown-item" href="{% url 'accounts:password_change' %}">Change Password</a>
                                <a class="dropdown-item" href="{% url 'accounts:user_logout' %}">Logout</a>
                            </div>
                        </li>
                    </ul>
                    <ul/>
                    {% endif %}
                </ul>
    </div>
</nav>
<div class="container-fluid">
	<br>
	<h1 align="center" style=font-size:72px>STUDENT WELFARE SOCIETY</h1>
    {% block content %}
        {#        </div>#}
        {#        <img src="{% static 'pics/1.jpg' %}" width="100%" class="img-fluid">#}
        <div class="back">
            <div class="row">
                <div class="column" style="background-color: rgba(230, 202, 202, 0.80);">
                    <h1 align="center">Gangotri Hostel</h1>
                    <h2 align="center">(GH)</h2>
                    <img src="{% static 'pics/1.jpg' %}" width="100%" class="img-fluid">
                    <br><br>
                    <h4>Facilities</h4>
                    <ul style="list-style-type:none;">
                        <li>-> Badminton Court</li>
                        <li>-> Television Room</li>
                        <li>-> Washing Machine</li>
                        <li>-> Refrigerator</li>
                    </ul>
                </div>
                <div class="column" style="background-color: rgba(141, 182, 205, 0.80)">
                    <h1 align="center">Arawali Hostel</h1>
                    <h2 align="center">(BH1)</h2>
                    <img src="{% static 'pics/1.jpg' %}" width="100%" class="img-fluid">
                    <br><br>
                    <h4>Facilities</h4>
                    <ul style="list-style-type:none;">
                        <li>-> Badminton Court</li>
                        <li>-> Television Room</li>
                        <li>-> Snooker Table</li>
                        <li>-> Washing Machine</li>
                        <li>-> Refrigerator</li>
                    </ul>
                </div>
                <div class="column" style="background-color: rgba(141, 205, 171, 0.80)">
                    <h1 align="center">Nilgiri Hostel</h1>
                    <h2 align="center">(BH2)</h2>
                    <img src="{% static 'pics/1.jpg' %}" width="100%" class="img-fluid">
                    <br><br>
                    <h4>Facilities</h4>
                    <ul style="list-style-type:none;">
                        <li>-> Badminton Court</li>
                        <li>-> Television Room</li>
                        <li>-> Washing Machine</li>
                        <li>-> Refrigerator</li>
                    </ul>
                </div>
                <div class="column" style="background-color: rgba(174, 141, 205, 0.70)">
                    <h1 align="center">Shivalik Hostel</h1>
                    <h2 align="center">(BH3)</h2>
                    <img src="{% static 'pics/1.jpg' %}" width="100%" class="img-fluid">
                    <br><br>
                    <h4>Facilities</h4>
                    <ul style="list-style-type:none;">
                        <li>-> Badminton Court</li>
                        <li>-> Television Room</li>
                        <li>-> Washing Machine</li>
                        <li>-> Refrigerator</li>
                    </ul>
                </div>
            </div>
        </div>

        {#        <div>#}
    {% endblock %}
</div>

<br><br><br>
<div class="footers">
    <p>Online Hostel Leave Application Portal </p>
</div>
</body>
</html>

templates/permission_denied.html
{% extends 'base.html' %}
{% block content %}
    <h3>Permission denied</h3>
{% endblock %}